### ISSUE TITLE
microsoft.ad.user doesn't work idempotently when setting "accountExpires" attribute

### ISSUE THREAD

**Issue by caidingyu** [ansible-collections/microsoft.ad#57]
##### SUMMARY

The microsoft.ad.user module doesn't idempotently when setting "accountExpires" attribute. The Ansible task always outputs "changed" status even when the actual value is not change.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`microsoft.ad.user`

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.2]
  config file = /Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg
  configured module search path = ['/Users/ericca/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ericca/sources/OrionHealth/nzms-ansible/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/ericca/sources/OrionHealth/nzms-ansible/galaxy/collections
  executable location = /Users/ericca/sources/OrionHealth/nzms-ansible/.venv/bin/ansible
  python version = 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/ericca/sources/OrionHealth/nzms-ansible/.venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection   Version
------------ -------
microsoft.ad 1.2.0
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = ['/Users/ericca/sources/OrionHealth/nzms-ansible/galaxy/collections']
CONFIG_FILE() = /Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg
DEFAULT_ROLES_PATH(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = ['/Users/ericca/sources/OrionHealth/nzms-ansible/galaxy/roles']
DEFAULT_TIMEOUT(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = 30
DEPRECATION_WARNINGS(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = False
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/Users/ericca/sources/OrionHealth/nzms-ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
Target host: Microsoft Windows Server 2019 Datacenter
AD: AWS managed Active Directory, OS Windows Server 2019
Ansible master host: Mac OS Ventura 13.5 arm64 Darwin Kernel Version 22.6.0
```

##### STEPS TO REPRODUCE

```yaml
- name: Manage AD user accounts for individual end users
  microsoft.ad.user:
    name: "{{ item.name }}"
    upn: "{{ item.name }}@{{ ad_domain }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    email: "{{ item.email }}"
    company: "{{ item.company }}"
    # Generate a random password
    password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, length=15) }}"
    path: "OU=Users,{{ ad_root_ou }}"
    # When 'present': creates or updates the user account; When 'absent': removes the user account if it exists.
    state: "{{ item.state | default('present') }}"
    # Always append 'Domain Users' as the default AD user group
    groups: 
      set: "{{ item.groups | default([]) + ['Domain Users'] }}"
    enabled: "{{ item.enabled | default(false) }}"
    update_password: on_create
    user_cannot_change_password: false
    domain_server: "{{ ad_domain }}"
    attributes:
      set:
        accountExpires:
          # Set the value to '0' to make the account never expires. Otherwise the value should be a 'date_time' type.
          # Refer to https://learn.microsoft.com/en-us/windows/win32/adschema/a-accountexpires
          type: "{{ item.expiry is defined | ternary('date_time', 'int') }}"
          value: "{{ item.expiry is defined | ternary(item.expiry, '0') }}"
  loop: "{{ ad_user_accounts }}"
  when: ad_user_accounts is defined
  tags: ad_user
```
I use a list group variable `ad_user_accounts` to manage multiple AD user accounts.

##### EXPECTED RESULTS

The task should not change anything and output in green if no any value of the `ad_user_accounts` group var is changed.

##### ACTUAL RESULTS

The tasks always output in yellow (changed) even no any value of the `ad_user_accounts` group var is changed.

Tried to change to use `add` instead of `set` under `attributes` and got the same result.

If I comment out the entire section to set `attributes` then it works expectedly and idempotently.
```
    attributes:
      set:
        accountExpires:
          # Set the value to '0' to make the account never expires. Otherwise the value should be a 'date_time' type.
          # Refer to https://learn.microsoft.com/en-us/windows/win32/adschema/a-accountexpires
          type: "{{ item.expiry is defined | ternary('date_time', 'int') }}"
          value: "{{ item.expiry is defined | ternary(item.expiry, '0') }}"
```

**Comment by jborean93** [comment]
If you run with the `--diff` option it should show you what the before value is. That might help to show you what it is comparing it with.

**Comment by caidingyu** [comment]
Tried to add `--diff` option to run the Ansible playbook and got below output indicating the changes:
```
     "attributes": {
         "accountExpires": [
-            133352352000000000
+            "2023-07-31T00:00:00.0000000Z"
         ]
     }
```

**Comment by jborean93** [comment]
So unfortunately I think this is a limitation right now with how attributes are compared. The module has no logic to know if the attribute is a datetime vs integer values as AD stores them as pure integer. The comparison will always show a diff because that string never matches the integer value it is comparing with. More logic most likely needs to be applied to the diff calculation to check the desired type rather than just checking the raw value.

**Comment by jborean93** [comment]
The PR https://github.com/ansible-collections/microsoft.ad/pull/62 should fix this problem for you. The comparison between the raw value and the one specified should now be done on the converted date_time to int value.

**Comment by mariomelofilho** [comment]
This is still a problem, i'm trying to update "password_never_expires" and "user_cannot_change_password" with existing user but module return erro: "New-ADUser failed: The specified account already exists"
